version: "3.9"

services:
  db:
    image: mysql:8.0.25
    volumes:
      - db_volume:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=crawler
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: crawler
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"

volumes:
  db_volume: